<!DOCTYPE html>

<html>
<head>
	<title><?php echo __('order page title'); ?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0"> 


<!-- 	<link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet"> -->


	<?php 
	// Include CSS/JS for orderform
	$this->element('header_includes.phtml'); 
	?>
</head>

<body>
<div class="bestelform_header" style="overflow-x: hidden;">
	<img src="https://www.jouwsitehier.nl/files/logo.png"></img><br />
	

<ul id="bestelform_menu" class="elementor-nav-menu" data-smartmenus-id="15439425451761736">
    
    <li><a href="https://www.jouwsitehier.nl/ontdekken/">Ontdekken</a></li>
    <li><a href="https://www.jouwsitehier.nl/inspiratie/" >Inspiratie</a></li>
    <li><a href="https://www.jouwsitehier.nl/prijzen/" >Prijzen</a></li>
    <li><a href="https://www.jouwsitehier.nl/diensten/" >Diensten</a></li>
    <li><a href="https://www.jouwsitehier.nl/over-ons/" >Over ons</a></li>
    <li><a href="https://www.jouwsitehier.nl/contact/" >Contact</a></li></ul>

<div class="bestelform_headerbutton"><a href="https://www.jouwsitehier.nl/ontdekken/">Offerte aanvragen</a></div>

	
</div>
<div class="o_form_container">
